name: BetonQuestQT
version: 0.1
main: majster2nn.dev.betonQuestQT.BetonQuestQT
api-version: '1.20'
authors: [majster2nn]
depend:
  - BetonQuest

commands:
  QuestMenu:
    description: ""
  Reload:
    description: "Reloads plugin"
    permission: bqqt.restart

permissions:
  bqqt.restart:
    description: "Allows reloads of plugin"
    default: op